### PR TITLE
Fix integration tests

### PR DESCRIPTION
**Pull request by connersaeli**
This PR fixes a silently failing integration test that also blocked other tests from running. It also fixes the subsequent failing tests that were masked by this bug. This PR does not fix the high-level problem that the integration tests silently fail when a test class is not properly constructed, but I believe that should be addressed in a separate PR.

## Description

* Refactor internal dashboard test to properly set up the test
* Fix the content-type that the test is comparing to match Rocky 8 tests from before. There was previously logic to compare different content-types returned by the different operating systems (CentOS 7 and Rocky 8). These content-types rules for Rocky 8 were not properly copied before and caused the tests to erroneously fail. More info [here](https://github.com/ubccr/xdmod-supremm/pull/373/files#diff-db90236cb14dda42665bde3339f5cc9603f0a336580bd475c1739032b9234d92L402).
* Fix a warning in the `EfficiencyControllerProviderTest` by matching the test class to the test's filename

## Motivation and Context

This bug in the test was introduced in https://github.com/ubccr/xdmod-supremm/pull/373 with the upgrade from `phpunit` version ~4 to version 9.6.

Arguments are passed to that test class's constructor, however `phpunit`'s TestCase class does not accept any arguments and causes the test to fail. This is problematic because the test fails silently and does not execute the other tests. This is silently failing error from the test:
```
{"success":false,"count":0,"total":0,"totalCount":0,"results":[],"data":[],"message":"Too few arguments to function IntegrationTests\\REST\\internal_dashboard\\DashboardSupremmTest::__construct(), 0 passed in \/root\/xdmod\/vendor\/phpunit\/phpunit\/src\/Framework\/TestBuilder.php on line 138 and exactly 3 expected","code":0}
```
In addition to this test failing, there were subsequent tests that were also failing but never got executed. This PR includes fixes for those tests as well.

https://app.asana.com/0/159049597309611/1208001546005416

## Tests performed

Tested by running the integration test `runtests.sh` script in a container and verifying that all tests pass.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project as found in the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by jpwhite4 — APPROVED** [review]

**Comment by connersaeli** [comment]
New PR for this: https://github.com/ubccr/xdmod-supremm/pull/392
